### ISSUE TITLE
2023.4.0 - Error setting up entry PC for hass_agent

### ISSUE THREAD

**Issue by syphernl** [LAB02-Research/HASS.Agent-Integration#24]
After upgrading HASS from 2023.3.6 to 2023.4.0 this integration is broken.

```
Traceback (most recent call last):
  File "/srv/hass/lib/python3.10/site-packages/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/hass/.homeassistant/custom_components/hass_agent/__init__.py", line 162, in async_setup_entry
    await async_subscribe_topics(hass, sub_state)
  File "/srv/hass/lib/python3.10/site-packages/homeassistant/components/mqtt/subscription.py", line 133, in async_subscribe_topics
    await sub.subscribe()
  File "/srv/hass/lib/python3.10/site-packages/homeassistant/components/mqtt/subscription.py", line 60, in subscribe
    self.unsubscribe_callback = await self.subscribe_task
  File "/srv/hass/lib/python3.10/site-packages/homeassistant/components/mqtt/client.py", line 166, in async_subscribe
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot subscribe to topic 'hass.agent/devices/PC', MQTT is not enabled
```

**Comment by DrR0X-glitch** [comment]
Did you manage to fix this? Looks to me like you didn't have mqtt enabled?

**Comment by danielbrunt57** [comment]
This should be fixed by https://github.com/danielbrunt57/HASS.Agent-Integration/releases/tag/v2024.4.0

**Comment by wwelles** [comment]
> This should be fixed by https://github.com/danielbrunt57/HASS.Agent-Integration/releases/tag/v2024.4.0

I still have this issue. I think the original project is abandoned, could you submit a PR to https://github.com/hass-agent/HASS.Agent @danielbrunt57 ?
